### PR TITLE
Fix skipIf condition for tests that require GitHub login

### LINKED ISSUE #641: Unit test failures on recent merge
The CI failed after merging a PR with the following errors:

```
======================================================================
ERROR: test_post_submit (app.tests.SubmitNewLicenseViewsTestCase)
POST Request for submit a new license
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/tests.py", line 1354, in test_post_submit
    self.assertEqual(licenseRequest.licenseAuthorName, "")
AttributeError: 'NoneType' object has no attribute 'licenseAuthorName'

======================================================================
ERROR: test_split_tree_editor_attributes (app.tests.LicenseXMLEditorTestCase)
Test for adding, editing and deleting attributes using split view tree editor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/tests.py", line 774, in test_split_tree_editor_attributes
    WebDriverWait(driver, 10).until(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 121, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:202:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:555:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16


======================================================================
ERROR: test_promote_license_namespace_feature (app.tests.PromoteLicenseNamespaceViewsTestCase)
Check if the license namespace is promoted when the promote action is taken
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/tests.py", line 1444, in test_promote_license_namespace_feature
    resp = self.client.post(reverse("promoted-license-namespace-xml"),
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 951, in post
    response = super().post(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 482, in post
    return self.generic(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 609, in generic
    return self.request(**r)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 894, in request
    self.check_exception(response)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 741, in check_exception
    raise exc_value
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/views.py", line 1030, in promoteNamespaceRequests
    statusCode, _ = utils.createIssue(
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/utils.py", line 369, in createIssue
    headers = {'Authorization': 'token ' + token}
TypeError: can only concatenate str (not "NoneType") to str
```

Note that `test_promote_license_namespace_feature` could just be removed since we are no longer using this feature.

### PR DESCRIPTION
**Pull request by bact**
- GitHub credential related tests should be skipped if ANY of the condition fails.
  - Currently it check for ALL conditions.
  - In `@skipIf` decoractor, change `and` to `or`
- The test license text is also revised, just in case, to use generated text that lacks legal signifiers to avoid any matching.
  - If a license text is a perfect match or a close match, a LicenseRequest will never be created -- causing the test to fail.
  - See the condition at line src/app/views.py line 138-140, which will give early return at line 163. The LicenseRequest creation is at line 172.

To fix #641.

### CODE REVIEW

File: src/app/tests.py [hunk 1]
```diff
@@ -1238,7 +1240,7 @@ def tearDown(self):
         self.selenium.quit()
         super(ArchiveLicenseRequestsSeleniumTestCase, self).tearDown()
 
-    @skipIf(not getAccessToken() and not getGithubUserId() and not getGithubUserName(), "You need to set gihub parameters in the secret.py file for this test to be executed properly.")
+    @skipIf(not getAccessToken() and not getGithubUserId() and not getGithubUserName(), "You need to set GitHub parameters in the secret.py file for this test to be executed properly.")
```
Comment (goneall) [inline src/app/tests.py]: Should this also be `or` instead of `and`?

File: src/app/tests.py [hunk 2]
```diff
@@ -1264,7 +1266,7 @@ def test_archive_license_requests_feature(self):
             )
             self.assertEqual(LicenseRequest.objects.get(id=license_obj.id).archive, True)
 
-    @skipIf(not getAccessToken() and not getGithubUserId() and not getGithubUserName(), "You need to set gihub parameters in the secret.py file for this test to be executed properly.")
+    @skipIf(not getAccessToken() and not getGithubUserId() and not getGithubUserName(), "You need to set GitHub parameters in the secret.py file for this test to be executed properly.")
```
Comment (goneall) [inline src/app/tests.py]: Should this also be `or` instead of `and`?

**Review by goneall — CHANGES_REQUESTED** [review]
2 `@skipif`s are still `and` instead of `or`.  I didn't know if this was intentional.

File: src/app/tests.py (hunk 2 above)
Comment (bact) [reply src/app/tests.py]: Thank you! They should be `or`. Fixed.

**Review by goneall — APPROVED** [review]
Thanks @bact
