### ISSUE TITLE
Unit test failures on recent merge

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#641]
The CI failed after merging a PR with the following errors:

```
======================================================================
ERROR: test_post_submit (app.tests.SubmitNewLicenseViewsTestCase)
POST Request for submit a new license
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/tests.py", line 1354, in test_post_submit
    self.assertEqual(licenseRequest.licenseAuthorName, "")
AttributeError: 'NoneType' object has no attribute 'licenseAuthorName'

======================================================================
ERROR: test_split_tree_editor_attributes (app.tests.LicenseXMLEditorTestCase)
Test for adding, editing and deleting attributes using split view tree editor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/tests.py", line 774, in test_split_tree_editor_attributes
    WebDriverWait(driver, 10).until(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 121, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:202:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:555:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16


======================================================================
ERROR: test_promote_license_namespace_feature (app.tests.PromoteLicenseNamespaceViewsTestCase)
Check if the license namespace is promoted when the promote action is taken
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/tests.py", line 1444, in test_promote_license_namespace_feature
    resp = self.client.post(reverse("promoted-license-namespace-xml"),
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 951, in post
    response = super().post(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 482, in post
    return self.generic(
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 609, in generic
    return self.request(**r)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 894, in request
    self.check_exception(response)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/test/client.py", line 741, in check_exception
    raise exc_value
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/hostedtoolcache/Python/3.10.20/x64/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/views.py", line 1030, in promoteNamespaceRequests
    statusCode, _ = utils.createIssue(
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/utils.py", line 369, in createIssue
    headers = {'Authorization': 'token ' + token}
TypeError: can only concatenate str (not "NoneType") to str
```

Note that `test_promote_license_namespace_feature` could just be removed since we are no longer using this feature.

**Comment by bact** [comment]
Hmm.. this is weird.

`test_post_submit()` should be skipped as there is no GitHub token provided. (the test as a `@skipIf(not getAccessToken() ...` decorator)

I will look into this.

**Comment by bact** [comment]
Fixed the tests with #643.
The conditions in skipIf should use "or", not "and".
